# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "Level 100"),
                    ("200", "Level 200"),
                    ("300", "Level 300"),
                    ("400", "Level 400"),
                    ("500", "Level 500"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="programme",
            field=models.CharField(max_length=150),
        ),
    ]
