# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("credits", models.PositiveIntegerField(default=3)),
                ("programme", models.CharField(max_length=150)),
                ("level", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                ("lecturer", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
